//AUTH
export const START_AUTH = 'START_AUTH'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const EXPIRATION_TIME = 'EXPIRATION_TIME'
//GAME
export const SET_SETTING = 'SET_SETTING'
export const CHANGE_MODE = 'CHANGE_MODE'